### ISSUE TITLE
I am getting an error running example-darkmode

### ISSUE THREAD

**Issue by joemoraca** [leptos-rs/example-darkmode#2]
https://github.com/leptos-rs/example-darkmode/blob/1bcd282239dc0a5600396f26a932fc49c673303e/src/dark_mode.rs#L29

no method named `unchecked_into` found for struct `Document` in the current scope

I am new to rust and leptos so I am lost ;-(  I was watching the video and then tried to run this code and .... no love for me.

**Comment by gbj** [comment]
Thanks! I hadn't updated it to `0.2` yet but was fairly easy, so here you go!

**Comment by joemoraca** [comment]
Thanks. Perhaps some day I will be fluent enough to be able to help out.
